@startuml
actor Admin as actor
participant SARM as sarm

actor -> sarm: starts update x
sarm --> actor: requests data
actor -> sarm: inserts requested data
sarm --> actor: message: x successufully updated

@enduml