@startuml
actor Admin as actor
participant SARM as sarm

actor -> sarm: request a delete/deactivation for X
sarm --> actor: requests X id
actor -> sarm: inserts requested data
sarm --> actor: message: X successufully deactivated or deleted

@enduml